epochs: 20

phases:
  - image_size: 448
    augment_rate: 0.6
    batch_size: 60
    epoch_milestone: 0

optimizer:
  weight_decay: 0.00001

  # adam | rmsprop | ranger_lars | sgd
  type: ranger_lars
  # momentum: 0.9
  # nesterov: false

  lr_initial: 0.01

  lr_decay:
    enabled: false
    rate: 0.97
    interval: 2

  lr_exponential:
    enabled: true
    gamma: 0.93

  lr_warmup:
    enabled: true
    warmup_steps: 100

# Keys under 'dynamic' should be empty (will be updated in runtime)
# TODO: should be removed
dynamic:
  classes:

#
# Split type, defined in NIHDataset
#
dataset_split_type: official_val_from_test

#
#
#
classes:
  - Cardiomegaly
  - Edema
  - Effusion
  - Emphysema
  - Mass
  - Pneumothorax