#
# Testing params
#

# ClearML task ID
task_id:

# Checkpoint filename.
ckpt_file:

# Specify classes, leave empty to use all
classes:
  - Cardiomegaly
  - Edema
  - Effusion
  - Emphysema
  - Mass
  - Pneumothorax


params:
  batch_size: 4
  image_size: 380